#===============================================================================
# User Options
#===============================================================================

# Compiler can be set below, or via environment variable

# Specify NVHPC's mpicc
CC        = mpic++
OPTIMIZE  = yes
DEBUG     = no
DEVICE    = gpu
SM        = cc90
LAUNCHER = bash -c

#===============================================================================
# Program name & source code list
#===============================================================================

program = main

source = main.cpp

obj = $(source:.cpp=.o)

#===============================================================================
# Sets Flags
#===============================================================================

# Standard Flags
CFLAGS := $(EXTRA_CFLAGS) -std=c++14 -Wall 	-DNX=400        	-DNZ=200 	-DSIM_TIME=600 	-DDATA_SPEC=DATA_SPEC_THERMAL         -I../miniWeather-cuda/

# Linker Flags
LDFLAGS =

# Debug Flags
ifeq ($(DEBUG),yes)
  CFLAGS += -g -DDEBUG
  LDFLAGS  += -g
endif


# Optimization Flags
ifeq ($(OPTIMIZE),yes)
  CFLAGS += -O3
endif

ifeq ($(DEVICE),gpu)
  CFLAGS +=-Minfo -acc=gpu -gpu=$(SM)
else
  CFLAGS +=-acc
endif
#===============================================================================
# Targets to Build
#===============================================================================

$(program): $(obj)
	$(CC) $(CFLAGS) $(obj) -o $@ $(LDFLAGS)

%.o: %.cpp ../miniWeather-cuda/check_output.h
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -rf $(program) $(obj)

include ../include/miniWeather-NVIDIA

run: $(program)
	$(LAUNCHER) "$(COMMAND)"

run_mem: $(program)
	nvidia-smi --query-gpu=memory.used,memory.total --format=csv --loop-ms=1 > log.mem &
	$(LAUNCHER) "$(COMMAND)"
	pkill nvidia-smi
	../scripts/m.sh

